[extension]
name = "echo"
version = "0.1.0"
kind = "resolver"
description = "A new extension"
license = "MIT"
# homepage_url = "https://example.com/my-extension"
# repository_url = "https://github.com/my-username/my-extension"

# These are the default permissions for the extension.
# The user can enable or disable them as needed in the gateway
# configuration file.
[permissions]
network = false
stdout = false
stderr = false
environment_variables = false

[directives]
definitions = "definitions.graphql"
